### ISSUE TITLE
id already exists error

### ISSUE THREAD

**Issue by fopina** [fopina/tgbotplug#23]
To be investigated:

    [Wed Jan 20 05:09:10 2016] [error] [.] Traceback (most recent call last):
    [Wed Jan 20 05:09:10 2016] [error] [.]   File "/x/python/virtenv/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    [Wed Jan 20 05:09:10 2016] [error] [.]     return route.call(**args)
    [Wed Jan 20 05:09:10 2016] [error] [.]   File "/x/python/virtenv/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    [Wed Jan 20 05:09:10 2016] [error] [.]     rv = callback(*a, **ka)
    [Wed Jan 20 05:09:10 2016] [error] [.]   File "/x/python/virtenv/lib/python2.7/site-packages/tgbot/webserver.py", line 20, in update
    [Wed Jan 20 05:09:10 2016] [error] [.]     bots_dict[token].process_update(Update.from_dict(request.json))
    [Wed Jan 20 05:09:10 2016] [error] [.]   File "/x/python/virtenv/lib/python2.7/site-packages/tgbot/tgbot.py", line 80, in process_update
    [Wed Jan 20 05:09:10 2016] [error] [.]     self.process_message(update.message)
    [Wed Jan 20 05:09:10 2016] [error] [.]   File "/x/python/virtenv/lib/python2.7/site-packages/tgbot/tgbot.py", line 127, in process_message
    [Wed Jan 20 05:09:10 2016] [error] [.]     self.process(message, cmd, text)
    [Wed Jan 20 05:09:10 2016] [error] [.]   File "/x/python/virtenv/lib/python2.7/site-packages/tgbot/tgbot.py", line 171, in process
    [Wed Jan 20 05:09:10 2016] [error] [.]     self.cmds[cmd].method(message, text)
    [Wed Jan 20 05:09:10 2016] [error] [.]   File "/x/app-root/runtime/repo/bots/x/plugins/x.py", line 88, in x
    [Wed Jan 20 05:09:10 2016] [error] [.]     self.need_reply(self.x, message, out_message=m, selective=True)
    [Wed Jan 20 05:09:10 2016] [error] [.]   File "/x/python/virtenv/lib/python2.7/site-packages/tgbot/pluginbase.py", line 63, in need_reply
    [Wed Jan 20 05:09:10 2016] [error] [.]     reply_selective=selective,
    [Wed Jan 20 05:09:10 2016] [error] [.]   File "/x/python/virtenv/lib/python2.7/site-packages/peewee.py", line 4127, in create
    [Wed Jan 20 05:09:10 2016] [error] [.]     inst.save(force_insert=True)
    [Wed Jan 20 05:09:10 2016] [error] [.]   File "/x/python/virtenv/lib/python2.7/site-packages/peewee.py", line 4287, in save
    [Wed Jan 20 05:09:10 2016] [error] [.]     pk_from_cursor = self.insert(**field_dict).execute()
    [Wed Jan 20 05:09:10 2016] [error] [.]   File "/x/python/virtenv/lib/python2.7/site-packages/peewee.py", line 2980, in execute
    [Wed Jan 20 05:09:10 2016] [error] [.]     cursor = self._execute()
    [Wed Jan 20 05:09:10 2016] [error] [.]   File "/x/python/virtenv/lib/python2.7/site-packages/peewee.py", line 2470, in _execute
    [Wed Jan 20 05:09:10 2016] [error] [.]     return self.database.execute_sql(sql, params, self.require_commit)
    [Wed Jan 20 05:09:10 2016] [error] [.]   File "/x/python/virtenv/lib/python2.7/site-packages/peewee.py", line 3199, in execute_sql
    [Wed Jan 20 05:09:10 2016] [error] [.]     self.commit()
    [Wed Jan 20 05:09:10 2016] [error] [.]   File "/x/python/virtenv/lib/python2.7/site-packages/peewee.py", line 3048, in __exit__
    [Wed Jan 20 05:09:10 2016] [error] [.]     reraise(new_type, new_type(*exc_args), traceback)
    [Wed Jan 20 05:09:10 2016] [error] [.]   File "/x/python/virtenv/lib/python2.7/site-packages/peewee.py", line 3191, in execute_sql
    [Wed Jan 20 05:09:10 2016] [error] [.]     cursor.execute(sql, params or ())
    [Wed Jan 20 05:09:10 2016] [error] [.] IntegrityError: duplicate key value violates unique constraint "message_pkey"
    [Wed Jan 20 05:09:10 2016] [error] [.] DETAIL:  Key (id)=(x) already exists.

**Comment by fopina** [comment]
Fixed in 7a103fd66277e97b5e19fb36285baa2fb3563ae0 (with wrong commit message)
